### PR TITLE
Add Carthage support

### PR DESCRIPTION
**Pull request by Grubas7**
🎉

### CODE REVIEW

**Comment by Grubas7** [comment]
@jhersh, @segiddins could you take a look?

**Comment by jhersh** [comment]
Are we sure that Carthage needs a new xcodeproj in the root folder? Does it not find the one in the Example folder? Otherwise, 👍

**Comment by Grubas7** [comment]
No, Carthage doesn't require xcodeproj in the root folder. However IMO adding framework target of library to `SSDynamicText>>>Example<<<.xcodeproj` project in `Example` folder is misleading.
Many of popular repositories ([SnapKit](https://github.com/SnapKit/SnapKit), [Alamofire](https://github.com/Alamofire/Alamofire), [SwiftyJSON](https://github.com/SwiftyJSON/SwiftyJSON), [RxSwift](https://github.com/ReactiveX/RxSwift), [PromiseKit](https://github.com/mxcl/PromiseKit) have structure like this.

But if you insist I can revert this change ;)

**Comment by Grubas7** [comment]
@jhersh Are you OK with this change?

**Pull request merged**
