### PR TITLE
Add Carthage support

### PR DESCRIPTION
**Pull request by Grubas7**
🎉

### CODE REVIEW

**Comment by segiddins** [comment]
Why did all of the source files change location?

**Comment by Grubas7** [comment]
`Pod/Classes` is suggested by Cocoapods folder for framework:
https://guides.cocoapods.org/making/using-pod-lib-create.html

AFAIK relocation won't break any compatibility. But without moving should work as well.

**Comment by jhersh** [comment]
That's just the default template for new pods, right? I would prefer we not change the folder structure.

I am not so familiar with Carthage, but doesn't it also impose its own requirements? I remember something about it picking the first (alphabetical) folder.

**Comment by Grubas7** [comment]
Carthage picks first found pbxproj and try to build framework scheme. 
I'll revert files location.

**Comment by Grubas7** [comment]
I had merge problem. PR moved here: https://github.com/splinesoft/SSDynamicText/pull/35

**Pull request closed without merging**
