### PR TITLE
Updated Xcode version for circle.

### PR DESCRIPTION
**Pull request by Grubas7**

### CODE REVIEW

**Comment by jhersh** [comment]
Thanks @grubas7 for fixing this! Can you do me a favor and make sure your commits are rebased on lastest `master`? That will help ensure that the coverage numbers are accurate.

**Comment by jhersh** [comment]
@grubas7 Also please change the simulator to use 9.0, as 9.1 is not supported under Xcode 7.0 (that requires Xcode 7.1, which Circle does not yet have).

**Comment by Grubas7** [comment]
@jhersh Sorry, maybe I did this to fast. I'll wait with next merges a bit.
I did in this way because I have README.md changes on my master branch and I didn't want to commit all the changes in one PR. Do you want to revert this change?

**Comment by jhersh** [comment]
This is fine, please just add the 9.0 simulator fix.

**Pull request merged**
