### PR TITLE
Release 1.1.1

### LINKED ISSUE #40: Memory leaks
Folks from company noticed memory problem in `SSDynamicText`. They was looking for potential strong retain cycles in other code, but they found leks in `SSDynamicLabel`.

I build app to check the problem, and there is leak even in the simplest code:
screen shot 2016-11-12 at 14 13 25

Looks like the problem is caused by strong retain cycle of `super`:
```
changer.fontChangeBlock = ^(UIFont *font) {
    [super setFont:font];
};
```

Same code appears in `SSDynamicTextView` and `SSDynamicTextField` classes, so I assume there is the same retain cycle.

Simple app in attachment:
[SSDynamicLeak.zip](https://github.com/splinesoft/SSDynamicText/files/587225/SSDynamicLeak.zip)

### PR DESCRIPTION
**Pull request by segiddins**
Closes #40

### CODE REVIEW

**Comment by segiddins** [comment]
Times out waiting for simulator to start so I can't release

**Review by Grubas7 — APPROVED** [review]

**Comment by Grubas7** [comment]
Found on Circle docs:

> If you see your test command failing with errors similar to this:
`iPhoneSimulator: Timed out waiting 120 seconds for simulator to boot, current state is 1`
>Then the version of the simulator you are trying to use on CircleCI might not be present in the build machines. In addition to the default version of simulator for every Xcode installation, we also make simulators of the following iOS versions available for all Xcode versions:
>- 7.1
>- 8.4
>Please try using any of the versions of simulator that are present on the machines — the error might disappear.

I could update .yml file if you like to.

**Comment by jhersh** [comment]
Let's update to the latest Xcode/iOS that Circle supports.

**Comment by Grubas7** [comment]
https://github.com/splinesoft/SSDynamicText/pull/43

**Comment by segiddins** [comment]
Released.

**Comment by Grubas7** [comment]
Thanks! 🎉

**Pull request merged**
