### PR TITLE
Change iOS Simulator to 9.0 for circle

### PR DESCRIPTION
**Pull request by Grubas7**

### CODE REVIEW

**Comment by jhersh** [comment]
Looks like the formatting has changed. Let's change this to

```
xcrun instruments -w "iPhone 6s (9.0)" || exit 0
```

**Comment by Grubas7** [comment]
Shouldn't we change also `-destination "platform=iOS Simulator,name=iPhone 6"` to `iPhone 6s`?

**Comment by jhersh** [comment]
Sure.

**Comment by jhersh** [comment]
:+1:

**Comment by Grubas7** [comment]
This looks like something go wrong:
screen shot 2015-11-18 at 21 29 22

**Comment by jhersh** [comment]
We use this command only to boot the proper simulator before tests are run. It's fine :+1:

**Comment by Grubas7** [comment]
Squashed, ready to merge ;)

**Comment by jhersh** [comment]
:+1:

**Comment by Grubas7** [comment]
I checked locally and you are right. `xcrun instruments -w "iPhone 6s (9.0)"` runs simulator correctly, and I have same error.
Merge.

**Pull request merged**
